<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('contracts', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid');
            $table->enum('contract_type', ['housing', 'commercial']);
            $table->unsignedBigInteger('user_id');
            $table->enum('contract_ownership', ['owner', 'tenant'])->nullable();
            $table->enum('instrument_type', ['electronic', 'old_handwritten', 'strong_argument', 'electronic_tax_register', 'property_ownership_owner_are_deceased_endowment', 'property_ownership_owner_is_endowment', 'sale_agreement', 'electronic_deed_from_the_ministry_of_justice', 'economic_cities_authority_suspended', 'sublease_agreement', 'lease_renewal', 'property_ownership_owner_are_suspended', 'property_ownership_owner_are_deceased'])->nullable();
            $table->enum('status', ['retrieved', 'cancel'])->nullable();
            $table->string('instrument_number')->nullable();
            $table->date('instrument_history')->nullable();
            $table->string('date_first_registration')->nullable();
            $table->string('real_estate_registry_number')->nullable();
            $table->string('number_of_units_in_realestate')->nullable();
            $table->boolean('property_owner_is_deceased')->default(false);
            $table->unsignedBigInteger('property_usages_id')->nullable();
            $table->unsignedBigInteger('property_city_id')->nullable();
            $table->unsignedBigInteger('property_place_id')->nullable();
            $table->unsignedBigInteger('property_type_id')->nullable();
            $table->string('neighborhood')->nullable();
            $table->string('building_number')->nullable();
            $table->string('postal_code')->nullable();
            $table->string('extra_figure')->nullable();
            $table->string('address_url')->nullable();
            $table->string('number_of_floors')->nullable();
            $table->string('street')->nullable();
            $table->string('property_owner_id_num')->nullable();
            $table->string('property_owner_mobile')->nullable();
            $table->string('property_owner_iban')->nullable();
            $table->boolean('add_legal_agent_of_owner')->nullable();
            $table->string('id_num_of_property_owner_agent')->nullable();
            $table->date('dob_gregorian_of_property_owner_agent')->nullable();
            $table->string('dob_hijri_of_property_owner_agent')->nullable();
            $table->string('mobile_of_property_owner_agent')->nullable();
            $table->string('agency_number_in_instrument_of_property_owner')->nullable();
            $table->date('agency_instrument_date_of_property_owner')->nullable();
            $table->string('agent_iban_of_property_owner')->nullable();
            $table->string('tenant_id_num')->nullable();
            $table->date('tenant_dob_gregorian')->nullable();
            $table->string('tenant_dob')->nullable();
            $table->string('tenant_mobile')->nullable();
            $table->string('name_owner')->nullable();
            $table->string('name_real_estate')->nullable();
            $table->boolean('add_legal_agent_of_tenant')->nullable();
            $table->string('id_num_of_property_tenant_agent')->nullable();
            $table->date('dob_gregorian_of_property_tenant_agent')->nullable();
            $table->string('dob_of_property_tenant_agent')->nullable();
            $table->string('mobile_of_property_tenant_agent')->nullable();
            $table->string('agency_number_in_instrument_of_property_tenant')->nullable();
            $table->date('agency_instrument_date_of_property_tenant')->nullable();
            $table->enum('tenant_entity', ['person', 'institution'])->nullable();
            $table->string('tenant_entity_unified_registry_number')->nullable();
            $table->unsignedBigInteger('tenant_entity_region_id')->nullable();
            $table->unsignedBigInteger('tenant_entity_city_id')->nullable();
            $table->enum('authorization_type', ['owner_and_representative_of_record', 'agent_for_the_tenant', 'agent_or_authorized_by_registry_owner'])->nullable();
            $table->text('copy_of_the_authorization_or_agency')->nullable();
            $table->text('copy_of_the_owner_record')->nullable();
            $table->unsignedBigInteger('city_of_the_tenant_legal_agent')->nullable();
            $table->unsignedBigInteger('region_of_the_tenant_legal_agent')->nullable();
            $table->string('unit_number')->nullable();
            $table->unsignedBigInteger('unit_type_id')->nullable();
            $table->string('tootal_rooms')->nullable();
            $table->string('floor_number')->nullable();
            $table->string('unit_area')->nullable();
            $table->string('electricity_meter_number')->nullable();
            $table->string('water_meter_number')->nullable();
            $table->string('number_of_unit_air_conditioners')->nullable();
            $table->string('contract_starting_date', 20)->nullable();
            $table->unsignedBigInteger('contract_term_in_years')->nullable();
            $table->string('annual_rent_amount_for_the_unit')->nullable();
            $table->unsignedBigInteger('payment_type_id')->nullable();
            $table->string('daily_fine')->nullable();
            $table->boolean('sub_delay')->nullable();
            $table->text('other_conditions')->nullable();
            $table->json('other_conditions_list')->nullable();
            $table->boolean('premium_membership_for_free')->nullable();
            $table->string('deposit')->nullable();
            $table->string('Guarantee_amount')->nullable();
            $table->unsignedBigInteger('contract_period_id')->nullable();
            $table->unsignedBigInteger('real_id')->nullable();
            $table->unsignedBigInteger('real_units_id')->nullable();
            $table->unsignedBigInteger('unit_usage_id')->nullable();
            $table->string('client_account_holder_name')->nullable();
            $table->text('draft_before_paid')->nullable();
            $table->text('draft_after_paid')->nullable();
            $table->string('bank_account_number')->nullable();
            $table->string('The_number_of_the_toilet')->nullable();
            $table->string('The_number_of_halls')->nullable();
            $table->string('number_of_councils')->nullable();
            $table->string('The_number_of_kitchens')->nullable();
            $table->string('Gasmeter')->nullable();
            $table->string('Number_parking_spaces')->nullable();
            $table->integer('rating')->nullable();
            $table->text('rating_note')->nullable();
            $table->date('expiry_date')->nullable();
            $table->boolean('Services')->default(false);
            $table->integer('step')->default(0);
            $table->boolean('is_completed')->default(false);
            $table->boolean('is_draft')->default(false);
            $table->boolean('is_delete')->default(false);
            $table->boolean('is_real')->default(false);
            $table->text('file')->nullable();
            $table->boolean('is_review')->default(false);
            $table->longText('notes')->nullable();
            $table->enum('app_or_web', ['app', 'web'])->default('app');
            $table->timestamps();
            $table->text('image_instrument')->nullable();
            $table->integer('age_of_the_property')->nullable();
            $table->string('number_of_units_per_floor')->nullable();
            $table->text('image_address')->nullable();
            $table->decimal('latitude', 11, 8)->nullable();
            $table->decimal('longitude', 11, 8)->nullable();
            $table->text('image_instrument_from_the_front')->nullable();
            $table->text('image_instrument_from_the_back')->nullable();
            $table->text('Image_from_the_agency')->nullable();
            $table->text('copy_power_of_attorney_from_heirs_to_agent')->nullable();
            $table->text('Image_inheritance_certificate')->nullable();
            $table->boolean('tenant_roles')->default(false);
            $table->unsignedBigInteger('tenant_role_id')->nullable();
            $table->json('tenant_role_ids')->nullable();
            $table->json('tenant_role_values')->nullable();
            $table->text('text_additional_terms')->nullable();
            $table->text('notes_edits')->nullable();
            $table->boolean('additional_terms')->default(false);
            $table->unsignedBigInteger('contract_status_id')->nullable();
            $table->enum('type_dob', ['hijri', 'gregorian'])->default('hijri');
            $table->enum('type_dob_property_owner', ['hijri', 'gregorian'])->default('hijri');
            $table->enum('type_dob_property_owner_agent', ['hijri', 'gregorian'])->nullable();
            $table->enum('type_tenant_dob', ['hijri', 'gregorian'])->default('hijri');
            $table->enum('type_dob_tenant_agent', ['hijri', 'gregorian'])->nullable();
            $table->enum('type_contract_starting_date', ['hijri', 'gregorian'])->default('hijri');
            $table->enum('type_instrument_history', ['hijri', 'gregorian'])->nullable();
            $table->enum('type_date_first_registration', ['hijri', 'gregorian'])->nullable();
            $table->enum('type_agency_instrument_date_of_property_owner', ['hijri', 'gregorian'])->nullable();
            $table->text('copy_of_the_endowment_registration_certificate')->nullable();
            $table->text('copy_of_the_trusteeship_deed')->nullable();
            $table->boolean('is_multiple_trusteeship_deed_copy')->default(false);
            $table->text('property_owner_dob')->nullable();
            $table->integer('split_ac')->nullable();
            $table->integer('window_ac')->nullable();
            $table->boolean('kitchen_tank')->default(false);
            $table->boolean('furnished')->default(false);
            $table->string('type_furnished')->nullable();
            $table->boolean('accept_retrun_contract')->default(false);
            $table->unsignedBigInteger('accept_retrun_contract_employee_id')->nullable();
            $table->unsignedBigInteger('draft_contract_status_id')->nullable();
            $table->enum('electricity_meter_ownership', ['owner', 'tenant'])->nullable();
            $table->enum('water_meter_ownership', ['owner', 'tenant'])->nullable();
            $table->string('duration_preset', 32)->nullable();
            $table->unsignedTinyInteger('duration_years')->nullable();
            $table->unsignedTinyInteger('duration_months')->nullable();
            $table->unsignedSmallInteger('total_months')->nullable();
            $table->text('copy_of_guardians_power_of_attorney_for_agent')->nullable();
            $table->string('The_number_of_toilets')->nullable();
            $table->string('deed_addition_method', 20)->nullable();
            $table->string('deed_number')->nullable();
            $table->string('ejar_contract_number')->nullable();
            $table->text('ejar_status_notes')->nullable();
            $table->string('status_attachment')->nullable();
            $table->string('ejar_contract_draft_number')->nullable();
            $table->string('draft_contact_number_mode', 20)->nullable();
            $table->string('draft_contact_number', 30)->nullable();
            $table->foreign('accept_retrun_contract_employee_id', 'contracts_accept_retrun_contract_employee_id_foreign')->references('id')->on('employees')->nullOnDelete();
            $table->foreign('city_of_the_tenant_legal_agent', 'contracts_city_of_the_tenant_legal_agent_foreign')->references('id')->on('cities')->cascadeOnDelete();
            $table->foreign('contract_period_id', 'contracts_contract_period_id_foreign')->references('id')->on('contract_periods')->cascadeOnDelete();
            $table->foreign('contract_status_id', 'contracts_contract_status_id_foreign')->references('id')->on('contract_statuses')->nullOnDelete();
            $table->foreign('contract_term_in_years', 'contracts_contract_term_in_years_foreign')->references('id')->on('contract_periods')->cascadeOnDelete();
            $table->foreign('draft_contract_status_id', 'contracts_draft_contract_status_id_foreign')->references('id')->on('draft_contract_statuses')->nullOnDelete();
            $table->foreign('payment_type_id', 'contracts_payment_type_id_foreign')->references('id')->on('payment_types')->cascadeOnDelete();
            $table->foreign('property_city_id', 'contracts_property_city_id_foreign')->references('id')->on('cities')->cascadeOnDelete();
            $table->foreign('property_place_id', 'contracts_property_place_id_foreign')->references('id')->on('regions')->cascadeOnDelete();
            $table->foreign('property_type_id', 'contracts_property_type_id_foreign')->references('id')->on('rea_estat_types')->cascadeOnDelete();
            $table->foreign('property_usages_id', 'contracts_property_usages_id_foreign')->references('id')->on('rea_estat_usages')->cascadeOnDelete();
            $table->foreign('real_id', 'contracts_real_id_foreign')->references('id')->on('real_estates')->cascadeOnDelete();
            $table->foreign('real_units_id', 'contracts_real_units_id_foreign')->references('id')->on('real_units')->cascadeOnDelete();
            $table->foreign('region_of_the_tenant_legal_agent', 'contracts_region_of_the_tenant_legal_agent_foreign')->references('id')->on('regions')->cascadeOnDelete();
            $table->foreign('tenant_entity_city_id', 'contracts_tenant_entity_city_id_foreign')->references('id')->on('cities')->cascadeOnDelete();
            $table->foreign('tenant_entity_region_id', 'contracts_tenant_entity_region_id_foreign')->references('id')->on('regions')->cascadeOnDelete();
            $table->foreign('unit_type_id', 'contracts_unit_type_id_foreign')->references('id')->on('unit_types')->cascadeOnDelete();
            $table->foreign('unit_usage_id', 'contracts_unit_usage_id_foreign')->references('id')->on('unit_usages')->cascadeOnDelete();
            $table->foreign('user_id', 'contracts_user_id_foreign')->references('id')->on('users')->cascadeOnDelete();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('contracts');
    }
};
